apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    name: {{ .Release.Name }}-service
    {{- include "voting-chart.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
  selector:
    name: {{ .Release.Name }}-pod
    {{- include "voting-chart.labels" . | indent 4 }}
