apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    name: {{ .Release.Name }}-service
    {{- include "voting-chart.labels" . | indent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    name: {{ .Release.Name }}-pod
    {{- include "voting-chart.labels" . | indent 4 }}
