apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-pod
  labels:
    name: {{ .Release.Name }}-pod
    {{- include "voting-chart.labels" . | indent 4 }}
spec:
  containers:
    - name: {{ .Release.Name }}
      image: {{ .Values.image.repository }}:{{ .Values.image.tag}}
